/**
 * This file generated by Apso.
 */
import { Test, TestingModule } from '@nestjs/testing';
import {
  PolicyDocument,
  PolicyDocumentCreate,
} from './dtos/PolicyDocument.dto';
import { PolicyDocumentController } from './PolicyDocument.controller';
import { PolicyDocumentService } from './PolicyDocument.service';
import { CrudRequest } from '@nestjsx/crud';

const baseRequest: CrudRequest = {
  parsed: {
    fields: [],
    paramsFilter: [],
    search: {},
    filter: [],
    or: [],
    join: [],
    sort: [],
    authPersist: undefined,
    limit: 10,
    offset: 0,
    page: 1,
    cache: undefined,
  },
  options: {},
};

describe('PolicyDocumentController', () => {
  let controller: PolicyDocumentController;
  let spyService: PolicyDocumentService;

  beforeEach(async () => {
    const ApiServiceProvider = {
      provide: PolicyDocumentService,
      useFactory: () => ({
        createOne: jest.fn(() => []),
        getOne: jest.fn(() => {}),
      }),
    };
    const module: TestingModule = await Test.createTestingModule({
      controllers: [PolicyDocumentController],
      providers: [PolicyDocumentService, ApiServiceProvider],
    }).compile();

    controller = module.get<PolicyDocumentController>(PolicyDocumentController);
    spyService = module.get<PolicyDocumentService>(PolicyDocumentService);
  });

  it('should be defined', () => {
    expect(controller).toBeDefined();
  });

  it('should call PolicyDocumentController get method', () => {
    const req: CrudRequest = { ...baseRequest };
    expect(controller.get(req)).not.toEqual(null);
    expect(spyService.getOne).toHaveBeenCalled();
  });

  it('should call PolicyDocumentController create method', () => {
    const req: CrudRequest = { ...baseRequest };

    const dto = new PolicyDocument();
    controller.create(req, dto);
    expect(controller.create(req, dto)).not.toEqual(null);
    expect(spyService.createOne).toHaveBeenCalled();
  });

  // Add your tests here
});
