/**
 * This file generated by Apso.
 */
import { Controller } from '@nestjs/common';
import {
  Crud,
  CrudController,
  Override,
  ParsedRequest,
  CrudRequest,
  ParsedBody,
  CreateManyDto,
} from '@nestjsx/crud';
import { ApiTags, ApiResponse, ApiOperation, ApiBody } from '@nestjs/swagger';
import {
  PolicyDocument,
  PolicyDocumentCreate,
} from './dtos/PolicyDocument.dto';
import { PolicyDocumentService } from './PolicyDocument.service';

@Crud({
  model: {
    type: PolicyDocument,
  },
  dto: {
    create: PolicyDocumentCreate,
    update: PolicyDocument,
    replace: PolicyDocument,
  },
  query: {
    /**
     * commenting out limit and pagination because of an issue with Crud lib: https://github.com/nestjsx/crud/issues/777
     */
    // TODO: make limit env driven?
    limit: 5,
    alwaysPaginate: true,
  },
})
@Controller('PolicyDocuments')
@ApiTags('PolicyDocuments')
export class PolicyDocumentController implements CrudController<PolicyDocument> {
  constructor(public service: PolicyDocumentService) {}

  get base(): CrudController<PolicyDocument> {
    return this;
  }

  @Override('getManyBase')
  @ApiOperation({ summary: 'Retrieve multiple PolicyDocuments' })
  getMany(@ParsedRequest() req: CrudRequest) {
    return this.base.getManyBase(req);
  }

  @Override('getOneBase')
  @ApiOperation({ summary: 'Retrieve a single PolicyDocument' })
  get(@ParsedRequest() req: CrudRequest) {
    return this.base.getOneBase(req);
  }

  @Override('createOneBase')
  @ApiOperation({ summary: 'Create a single PolicyDocument' })
  @ApiBody({
    type: PolicyDocumentCreate,
    description:
      'The Description for the Post Body. Please look into the DTO. You will see the @ApiOptionalProperty used to define the Schema.',
  })
  create(@ParsedRequest() req: CrudRequest, @ParsedBody() dto: PolicyDocument) {
    return this.base.createOneBase(req, dto);
  }

  @Override('createManyBase')
  @ApiOperation({ summary: 'Create multiplePolicyDocuments' })
  createMany(
    @ParsedRequest() req: CrudRequest,
    @ParsedBody() dto: CreateManyDto<PolicyDocument>,
  ) {
    return this.base.createManyBase(req, dto);
  }

  @Override('updateOneBase')
  @ApiOperation({ summary: 'Update a single PolicyDocument' })
  update(@ParsedRequest() req: CrudRequest, @ParsedBody() dto: PolicyDocument) {
    return this.base.updateOneBase(req, dto);
  }

  @Override('replaceOneBase')
  @ApiOperation({ summary: 'Replace a single PolicyDocument' })
  replace(
    @ParsedRequest() req: CrudRequest,
    @ParsedBody() dto: PolicyDocument,
  ) {
    return this.base.replaceOneBase(req, dto);
  }

  @Override('deleteOneBase')
  @ApiOperation({ summary: 'Delete a single PolicyDocument' })
  delete(@ParsedRequest() req: CrudRequest) {
    return this.base.deleteOneBase(req);
  }
}
