/**
 * This file generated by Apso.
 */
import { Module } from '@nestjs/common';
import { PolicyDocument } from './PolicyDocument.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { PolicyDocumentService } from './PolicyDocument.service';
import { PolicyDocumentController } from './PolicyDocument.controller';

@Module({
  imports: [TypeOrmModule.forFeature([PolicyDocument])],
  providers: [PolicyDocumentService],
  exports: [PolicyDocumentService],
  controllers: [PolicyDocumentController],
})
export class PolicyDocumentModule {}
