#!/usr/bin/env bash

startTime=$(date +%s)

currentDir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
rootDir=$(dirname "${currentDir}")
. "${currentDir}/../common.sh"
. "${currentDir}/db.sh"

info "DATABASE=${DATABASE_NAME}"
info "SCHEMA=${DATABASE_SCHEMA}_test"
info "USER=${DATABASE_USERNAME}"
info "PASSWORD=${DATABASE_PASSWORD}"
info "HOSTNAME=${DATABASE_HOST}"
info "PORT=${DATABASE_PORT}"

DATABASE=$DATABASE_NAME
SCHEMA="${DATABASE_SCHEMA}_test"
USER=$DATABASE_USERNAME
PASSWORD=$DATABASE_PASSWORD

HOSTNAME=$DATABASE_HOST
PORT=$DATABASE_PORT
ROOT_USERNAME="root"
ROOT_PASSWORD="root"
ROOT_DATABASE="postgres"


info "SET DATABASE ${DATABASE}"

# resetDatabase $DATABASE
createDatabaseUser $USER $PASSWORD $DATABASE $HOSTNAME $PORT $ROOT_USERNAME $ROOT_PASSWORD $ROOT_DATABASE
createDatabaseSchema $USER $DATABASE $SCHEMA $HOSTNAME $PORT $ROOT_USERNAME $ROOT_PASSWORD $ROOT_DATABASE