/**
 * This file generated by Apso.
 */
import { PolicyModule } from './Policy/Policy.module';
import { PolicyDocumentModule } from './PolicyDocument/PolicyDocument.module';
import { PolicyUserModule } from './PolicyUser/PolicyUser.module';
import { PolicyAssignmentModule } from './PolicyAssignment/PolicyAssignment.module';

export default [
  PolicyModule,
  PolicyDocumentModule,
  PolicyUserModule,
  PolicyAssignmentModule,
];
