import { ApiProperty } from '@nestjs/swagger';
/**
 * This file generated by Apso.
 */

export class PolicyUserCreate {
  @ApiProperty()
  user_name: string;
  @ApiProperty()
  email: string;
  @ApiProperty()
  role: string;
  @ApiProperty()
  status: string;
}

export class PolicyUser {
  @ApiProperty()
  id: number;
  @ApiProperty()
  user_name: string;
  @ApiProperty()
  email: string;
  @ApiProperty()
  role: string;
  @ApiProperty()
  status: string;
}
