import { CustomerStatusEnum } from '../../enums';

export const CustomerData = [
  {
    name: 'Michael Johnson',
    country: 'USA',
    streetAddress1: '555 Broad St',
    streetAddress2: 'Apt 301',
    city: 'San Francisco',
    state: 'CA',
    zipCode: '94105',
    phoneNumber: '111-222-3333',
    createdBy: 'Admin',
    status: CustomerStatusEnum.Active,
  },
  {
    name: 'Sophia Martinez',
    country: 'Mexico',
    streetAddress1: '123 Calle Principal',
    streetAddress2: '',
    city: 'Mexico City',
    state: 'DF',
    zipCode: '12345',
    phoneNumber: '555-666-7777',
    createdBy: null,
    status: CustomerStatusEnum.Active,
  },
  {
    name: 'David Lee',
    country: 'Canada',
    streetAddress1: '789 Bay St',
    streetAddress2: '',
    city: 'Vancouver',
    state: 'BC',
    zipCode: 'V6B 1W3',
    phoneNumber: '999-888-7777',
    createdBy: 'Manager',
    status: CustomerStatusEnum.Active,
  },
  {
    name: 'Emily Brown',
    country: 'Australia',
    streetAddress1: '456 King St',
    streetAddress2: 'Suite 100',
    city: 'Sydney',
    state: 'NSW',
    zipCode: '2000',
    phoneNumber: null,
    createdBy: 'Admin',
    status: CustomerStatusEnum.Archived,
  },
  {
    name: 'John Doe',
    country: 'USA',
    streetAddress1: '123 Main St',
    streetAddress2: '',
    city: 'New York',
    state: 'NY',
    zipCode: '10001',
    phoneNumber: '123-456-7890',
    createdBy: 'Admin',
    status: CustomerStatusEnum.Active,
  },
  {
    name: 'Jane Smith',
    country: 'Canada',
    streetAddress1: '456 Maple Ave',
    streetAddress2: '',
    city: 'Toronto',
    state: 'ON',
    zipCode: 'M1X 2X6',
    phoneNumber: null,
    createdBy: 'Manager',
    status: CustomerStatusEnum.Active,
  },
  {
    name: 'Alice Johnson',
    country: 'UK',
    streetAddress1: '789 Oak St',
    streetAddress2: 'Apt 101',
    city: 'London',
    state: 'LDN',
    zipCode: 'SW1A 1AA',
    phoneNumber: '987-654-3210',
    createdBy: 'Admin',
    status: CustomerStatusEnum.Archived,
  },
];
