import { FacilityStatusEnum } from '../../enums';

export const FacilityData = [
  {
    name: 'Storage D',
    contactName: null,
    streetAddress1: '321 Oak St',
    streetAddress2: '',
    city: 'Houston',
    state: 'TX',
    country: 'USA',
    zipCode: '77002',
    status: FacilityStatusEnum.Active,
    weight: '2000',
  },
  {
    name: 'Warehouse E',
    contactName: 'James Smith',
    streetAddress1: '987 Maple Ave',
    streetAddress2: '',
    city: 'Toronto',
    state: 'ON',
    country: 'Canada',
    zipCode: 'M5H 2K1',
    status: FacilityStatusEnum.Active,
    weight: '6000',
  },
  {
    name: 'Factory F',
    contactName: 'Emma Wilson',
    streetAddress1: '654 Elm St',
    streetAddress2: '',
    city: 'Melbourne',
    state: 'VIC',
    country: 'Australia',
    zipCode: '3000',
    status: FacilityStatusEnum.Archived,
    weight: '4000',
  },
  {
    name: 'Distribution Center G',
    contactName: 'William Johnson',
    streetAddress1: '741 Pine St',
    streetAddress2: 'Suite 201',
    city: 'Montreal',
    state: 'QC',
    country: 'Canada',
    zipCode: 'H3C 2M9',
    status: FacilityStatusEnum.Active,
    weight: '8000',
  },
  {
    name: 'Warehouse A',
    contactName: 'Bob Johnson',
    streetAddress1: '789 Elm St',
    streetAddress2: '',
    city: 'Los Angeles',
    state: 'CA',
    country: 'USA',
    zipCode: '90001',
    status: FacilityStatusEnum.Active,
    weight: '5000',
  },
  {
    name: 'Storage B',
    contactName: null,
    streetAddress1: '101 Pine St',
    streetAddress2: '',
    city: 'Chicago',
    state: 'IL',
    country: 'USA',
    zipCode: '60601',
    status: FacilityStatusEnum.Active,
    weight: '3000',
  },
  {
    name: 'Factory C',
    contactName: 'Sarah Lee',
    streetAddress1: '246 Oak St',
    streetAddress2: 'Suite 202',
    city: 'London',
    state: 'LDN',
    country: 'UK',
    zipCode: 'SW1A 1AA',
    status: FacilityStatusEnum.Archived,
    weight: '7000',
  },
];
