import { ApiProperty } from '@nestjs/swagger';
/**
 * This file generated by Apso.
 */

export class PolicyAssignmentCreate {
  @ApiProperty()
  assigned_date: string;
  @ApiProperty()
  due_date: string;
  @ApiProperty()
  status: string;
  @ApiProperty()
  policy_id: number;
  @ApiProperty()
  user_id: number;
}

export class PolicyAssignment {
  @ApiProperty()
  id: number;
  @ApiProperty()
  assigned_date: string;
  @ApiProperty()
  due_date: string;
  @ApiProperty()
  status: string;
  @ApiProperty()
  policy_id: number;
  @ApiProperty()
  user_id: number;
}
