/**
 * This file generated by Apso.
 */
import { Module } from '@nestjs/common';
import { PolicyAssignment } from './PolicyAssignment.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { PolicyAssignmentService } from './PolicyAssignment.service';
import { PolicyAssignmentController } from './PolicyAssignment.controller';

@Module({
  imports: [TypeOrmModule.forFeature([PolicyAssignment])],
  providers: [PolicyAssignmentService],
  exports: [PolicyAssignmentService],
  controllers: [PolicyAssignmentController],
})
export class PolicyAssignmentModule {}
