/**
 * This file generated by Apso.
 */
import { Test, TestingModule } from '@nestjs/testing';
import {
  PolicyAssignment,
  PolicyAssignmentCreate,
} from './dtos/PolicyAssignment.dto';
import { PolicyAssignmentController } from './PolicyAssignment.controller';
import { PolicyAssignmentService } from './PolicyAssignment.service';
import { CrudRequest } from '@nestjsx/crud';

const baseRequest: CrudRequest = {
  parsed: {
    fields: [],
    paramsFilter: [],
    search: {},
    filter: [],
    or: [],
    join: [],
    sort: [],
    authPersist: undefined,
    limit: 10,
    offset: 0,
    page: 1,
    cache: undefined,
  },
  options: {},
};

describe('PolicyAssignmentController', () => {
  let controller: PolicyAssignmentController;
  let spyService: PolicyAssignmentService;

  beforeEach(async () => {
    const ApiServiceProvider = {
      provide: PolicyAssignmentService,
      useFactory: () => ({
        createOne: jest.fn(() => []),
        getOne: jest.fn(() => {}),
      }),
    };
    const module: TestingModule = await Test.createTestingModule({
      controllers: [PolicyAssignmentController],
      providers: [PolicyAssignmentService, ApiServiceProvider],
    }).compile();

    controller = module.get<PolicyAssignmentController>(
      PolicyAssignmentController,
    );
    spyService = module.get<PolicyAssignmentService>(PolicyAssignmentService);
  });

  it('should be defined', () => {
    expect(controller).toBeDefined();
  });

  it('should call PolicyAssignmentController get method', () => {
    const req: CrudRequest = { ...baseRequest };
    expect(controller.get(req)).not.toEqual(null);
    expect(spyService.getOne).toHaveBeenCalled();
  });

  it('should call PolicyAssignmentController create method', () => {
    const req: CrudRequest = { ...baseRequest };

    const dto = new PolicyAssignment();
    controller.create(req, dto);
    expect(controller.create(req, dto)).not.toEqual(null);
    expect(spyService.createOne).toHaveBeenCalled();
  });

  // Add your tests here
});
