/**
 * This file generated by Apso.
 */
import { Controller } from '@nestjs/common';
import {
  Crud,
  CrudController,
  Override,
  ParsedRequest,
  CrudRequest,
  ParsedBody,
  CreateManyDto,
} from '@nestjsx/crud';
import { ApiTags, ApiResponse, ApiOperation, ApiBody } from '@nestjs/swagger';
import {
  PolicyAssignment,
  PolicyAssignmentCreate,
} from './dtos/PolicyAssignment.dto';
import { PolicyAssignmentService } from './PolicyAssignment.service';

@Crud({
  model: {
    type: PolicyAssignment,
  },
  dto: {
    create: PolicyAssignmentCreate,
    update: PolicyAssignment,
    replace: PolicyAssignment,
  },
  query: {
    /**
     * commenting out limit and pagination because of an issue with Crud lib: https://github.com/nestjsx/crud/issues/777
     */
    // TODO: make limit env driven?
    limit: 5,
    alwaysPaginate: true,
  },
})
@Controller('PolicyAssignments')
@ApiTags('PolicyAssignments')
export class PolicyAssignmentController implements CrudController<PolicyAssignment> {
  constructor(public service: PolicyAssignmentService) {}

  get base(): CrudController<PolicyAssignment> {
    return this;
  }

  @Override('getManyBase')
  @ApiOperation({ summary: 'Retrieve multiple PolicyAssignments' })
  getMany(@ParsedRequest() req: CrudRequest) {
    return this.base.getManyBase(req);
  }

  @Override('getOneBase')
  @ApiOperation({ summary: 'Retrieve a single PolicyAssignment' })
  get(@ParsedRequest() req: CrudRequest) {
    return this.base.getOneBase(req);
  }

  @Override('createOneBase')
  @ApiOperation({ summary: 'Create a single PolicyAssignment' })
  @ApiBody({
    type: PolicyAssignmentCreate,
    description:
      'The Description for the Post Body. Please look into the DTO. You will see the @ApiOptionalProperty used to define the Schema.',
  })
  create(
    @ParsedRequest() req: CrudRequest,
    @ParsedBody() dto: PolicyAssignment,
  ) {
    return this.base.createOneBase(req, dto);
  }

  @Override('createManyBase')
  @ApiOperation({ summary: 'Create multiplePolicyAssignments' })
  createMany(
    @ParsedRequest() req: CrudRequest,
    @ParsedBody() dto: CreateManyDto<PolicyAssignment>,
  ) {
    return this.base.createManyBase(req, dto);
  }

  @Override('updateOneBase')
  @ApiOperation({ summary: 'Update a single PolicyAssignment' })
  update(
    @ParsedRequest() req: CrudRequest,
    @ParsedBody() dto: PolicyAssignment,
  ) {
    return this.base.updateOneBase(req, dto);
  }

  @Override('replaceOneBase')
  @ApiOperation({ summary: 'Replace a single PolicyAssignment' })
  replace(
    @ParsedRequest() req: CrudRequest,
    @ParsedBody() dto: PolicyAssignment,
  ) {
    return this.base.replaceOneBase(req, dto);
  }

  @Override('deleteOneBase')
  @ApiOperation({ summary: 'Delete a single PolicyAssignment' })
  delete(@ParsedRequest() req: CrudRequest) {
    return this.base.deleteOneBase(req);
  }
}
