/**
 * This file generated by Apso.
 */
import { Test, TestingModule } from '@nestjs/testing';
import { Policy, PolicyCreate } from './dtos/Policy.dto';
import { PolicyController } from './Policy.controller';
import { PolicyService } from './Policy.service';
import { CrudRequest } from '@nestjsx/crud';

const baseRequest: CrudRequest = {
  parsed: {
    fields: [],
    paramsFilter: [],
    search: {},
    filter: [],
    or: [],
    join: [],
    sort: [],
    authPersist: undefined,
    limit: 10,
    offset: 0,
    page: 1,
    cache: undefined,
  },
  options: {},
};

describe('PolicyController', () => {
  let controller: PolicyController;
  let spyService: PolicyService;

  beforeEach(async () => {
    const ApiServiceProvider = {
      provide: PolicyService,
      useFactory: () => ({
        createOne: jest.fn(() => []),
        getOne: jest.fn(() => {}),
      }),
    };
    const module: TestingModule = await Test.createTestingModule({
      controllers: [PolicyController],
      providers: [PolicyService, ApiServiceProvider],
    }).compile();

    controller = module.get<PolicyController>(PolicyController);
    spyService = module.get<PolicyService>(PolicyService);
  });

  it('should be defined', () => {
    expect(controller).toBeDefined();
  });

  it('should call PolicyController get method', () => {
    const req: CrudRequest = { ...baseRequest };
    expect(controller.get(req)).not.toEqual(null);
    expect(spyService.getOne).toHaveBeenCalled();
  });

  it('should call PolicyController create method', () => {
    const req: CrudRequest = { ...baseRequest };

    const dto = new Policy();
    controller.create(req, dto);
    expect(controller.create(req, dto)).not.toEqual(null);
    expect(spyService.createOne).toHaveBeenCalled();
  });

  // Add your tests here
});
