/**
 * This file generated by Apso.
 */
import { Module } from '@nestjs/common';
import { Policy } from './Policy.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { PolicyService } from './Policy.service';
import { PolicyController } from './Policy.controller';

@Module({
  imports: [TypeOrmModule.forFeature([Policy])],
  providers: [PolicyService],
  exports: [PolicyService],
  controllers: [PolicyController],
})
export class PolicyModule {}
