import { ApiProperty } from '@nestjs/swagger';
/**
 * This file generated by Apso.
 */

export class PolicyDocumentCreate {
  @ApiProperty()
  document_name: string;
  @ApiProperty()
  content: string;
  @ApiProperty()
  version: number;
  @ApiProperty()
  published_date: string;
  @ApiProperty()
  policy_id: number;
}

export class PolicyDocument {
  @ApiProperty()
  id: number;
  @ApiProperty()
  document_name: string;
  @ApiProperty()
  content: string;
  @ApiProperty()
  version: number;
  @ApiProperty()
  published_date: string;
  @ApiProperty()
  policy_id: number;
}
