import { ApiProperty } from '@nestjs/swagger';
/**
 * This file generated by Apso.
 */

export class PolicyCreate {
  @ApiProperty()
  policy_name: string;
  @ApiProperty()
  description: string;
  @ApiProperty()
  created_date: string;
  @ApiProperty()
  last_updated: Date;
}

export class Policy {
  @ApiProperty()
  id: number;
  @ApiProperty()
  policy_name: string;
  @ApiProperty()
  description: string;
  @ApiProperty()
  created_date: string;
  @ApiProperty()
  last_updated: Date;
}
