/**
 * This file generated by Apso.
 */
import { Test, TestingModule } from '@nestjs/testing';
import { PolicyUser, PolicyUserCreate } from './dtos/PolicyUser.dto';
import { PolicyUserController } from './PolicyUser.controller';
import { PolicyUserService } from './PolicyUser.service';
import { CrudRequest } from '@nestjsx/crud';

const baseRequest: CrudRequest = {
  parsed: {
    fields: [],
    paramsFilter: [],
    search: {},
    filter: [],
    or: [],
    join: [],
    sort: [],
    authPersist: undefined,
    limit: 10,
    offset: 0,
    page: 1,
    cache: undefined,
  },
  options: {},
};

describe('PolicyUserController', () => {
  let controller: PolicyUserController;
  let spyService: PolicyUserService;

  beforeEach(async () => {
    const ApiServiceProvider = {
      provide: PolicyUserService,
      useFactory: () => ({
        createOne: jest.fn(() => []),
        getOne: jest.fn(() => {}),
      }),
    };
    const module: TestingModule = await Test.createTestingModule({
      controllers: [PolicyUserController],
      providers: [PolicyUserService, ApiServiceProvider],
    }).compile();

    controller = module.get<PolicyUserController>(PolicyUserController);
    spyService = module.get<PolicyUserService>(PolicyUserService);
  });

  it('should be defined', () => {
    expect(controller).toBeDefined();
  });

  it('should call PolicyUserController get method', () => {
    const req: CrudRequest = { ...baseRequest };
    expect(controller.get(req)).not.toEqual(null);
    expect(spyService.getOne).toHaveBeenCalled();
  });

  it('should call PolicyUserController create method', () => {
    const req: CrudRequest = { ...baseRequest };

    const dto = new PolicyUser();
    controller.create(req, dto);
    expect(controller.create(req, dto)).not.toEqual(null);
    expect(spyService.createOne).toHaveBeenCalled();
  });

  // Add your tests here
});
