/**
 * This file generated by Apso.
 */
import { Controller } from '@nestjs/common';
import {
  Crud,
  CrudController,
  Override,
  ParsedRequest,
  CrudRequest,
  ParsedBody,
  CreateManyDto,
} from '@nestjsx/crud';
import { ApiTags, ApiResponse, ApiOperation, ApiBody } from '@nestjs/swagger';
import { PolicyUser, PolicyUserCreate } from './dtos/PolicyUser.dto';
import { PolicyUserService } from './PolicyUser.service';

@Crud({
  model: {
    type: PolicyUser,
  },
  dto: {
    create: PolicyUserCreate,
    update: PolicyUser,
    replace: PolicyUser,
  },
  query: {
    /**
     * commenting out limit and pagination because of an issue with Crud lib: https://github.com/nestjsx/crud/issues/777
     */
    // TODO: make limit env driven?
    limit: 5,
    alwaysPaginate: true,
  },
})
@Controller('PolicyUsers')
@ApiTags('PolicyUsers')
export class PolicyUserController implements CrudController<PolicyUser> {
  constructor(public service: PolicyUserService) {}

  get base(): CrudController<PolicyUser> {
    return this;
  }

  @Override('getManyBase')
  @ApiOperation({ summary: 'Retrieve multiple PolicyUsers' })
  getMany(@ParsedRequest() req: CrudRequest) {
    return this.base.getManyBase(req);
  }

  @Override('getOneBase')
  @ApiOperation({ summary: 'Retrieve a single PolicyUser' })
  get(@ParsedRequest() req: CrudRequest) {
    return this.base.getOneBase(req);
  }

  @Override('createOneBase')
  @ApiOperation({ summary: 'Create a single PolicyUser' })
  @ApiBody({
    type: PolicyUserCreate,
    description:
      'The Description for the Post Body. Please look into the DTO. You will see the @ApiOptionalProperty used to define the Schema.',
  })
  create(@ParsedRequest() req: CrudRequest, @ParsedBody() dto: PolicyUser) {
    return this.base.createOneBase(req, dto);
  }

  @Override('createManyBase')
  @ApiOperation({ summary: 'Create multiplePolicyUsers' })
  createMany(
    @ParsedRequest() req: CrudRequest,
    @ParsedBody() dto: CreateManyDto<PolicyUser>,
  ) {
    return this.base.createManyBase(req, dto);
  }

  @Override('updateOneBase')
  @ApiOperation({ summary: 'Update a single PolicyUser' })
  update(@ParsedRequest() req: CrudRequest, @ParsedBody() dto: PolicyUser) {
    return this.base.updateOneBase(req, dto);
  }

  @Override('replaceOneBase')
  @ApiOperation({ summary: 'Replace a single PolicyUser' })
  replace(@ParsedRequest() req: CrudRequest, @ParsedBody() dto: PolicyUser) {
    return this.base.replaceOneBase(req, dto);
  }

  @Override('deleteOneBase')
  @ApiOperation({ summary: 'Delete a single PolicyUser' })
  delete(@ParsedRequest() req: CrudRequest) {
    return this.base.deleteOneBase(req);
  }
}
