/**
 * This file generated by Apso.
 */
import { Module } from '@nestjs/common';
import { PolicyUser } from './PolicyUser.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { PolicyUserService } from './PolicyUser.service';
import { PolicyUserController } from './PolicyUser.controller';

@Module({
  imports: [TypeOrmModule.forFeature([PolicyUser])],
  providers: [PolicyUserService],
  exports: [PolicyUserService],
  controllers: [PolicyUserController],
})
export class PolicyUserModule {}
